<?php

// Warning: This is a starting point, by no means a working module

/**
 * Redirect to parent before 404 is thrown.
 *
 */

class RedirectBeforeNotFound extends WireData implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => 'Redirect before not found',
            'summary' => 'Redirect before not found',
            'version' => 1,
            'autoload' => true,
        );
    }

    public function init() {
        $this->addHookBefore('ProcessPageView::pageNotFound', $this, 'beforeNotFound');
    }

    public function beforeNotFound($event) {
        $uri = "$_SERVER[REQUEST_URI]";
        $regex = '#(\/[a-z0-9_\-\/]+\/)#';
        if (preg_match($regex, $uri, $matches)) {
            $request_url = $matches[1];
            $page = $this->pages->get($request_url);
            if ($page->id && $page->is(Page::statusUnpublished)) {
                $this->session->redirect($page->parent->url);
            }
        }
        return;
    }
}
